apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "uprobe"
spec:
  options:
  - name: "disable-uprobe-multi"
    value: "0"
  uprobes:
  - path: "/bin/bash"
    symbols:
    - "readline"
